server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: local
  application:
    name: unmz-example-single
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 10
      max-active: 100
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      filter.stat.db-type: mysql
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 2000
      filter.wall.enabled: true
      filter.wall.db-type: mysql
      filter.wall.config.delete-allow: true
      filter.wall.config.drop-table-allow: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 1000
        profile-enable: true
      aop-patterns: net.unmz.java.example.*

mybatis:
  type-aliases-package: net.unmz.java.example.entity
  type-handlers-package: net.unmz.java.example.mapper
  mapper-locations: classpath*:/mapping/**/*.xml

mybatis-plus:
  type-aliases-package: net.unmz.java.example.entity
  type-handlers-package: net.unmz.java.example.mapper
  mapper-locations: classpath*:/mapping/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true





